# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{aspell_edit_dist}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Adam Pohorecki"]
  s.date = %q{2009-12-29}
  s.email = %q{adam@pohorecki.pl}
  s.extensions = ["ext/extconf.rb"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "README",
     "Rakefile",
     "VERSION",
     "ext/aspell_edit_dist.cpp",
     "ext/aspell_edit_dist.h",
     "ext/extconf.rb",
     "ext/leditdist.cpp",
     "ext/leditdist.hpp",
     "ext/weights.hpp",
     "lib/aspell_edit_dist_stub.rb",
     "test/edit_distance_test.rb",
     "test/test_helper.rb",
     "test/weights_test.rb"
  ]
  s.homepage = %q{http://github.com/psyho/aspell_edit_dist}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Gem that exposes limit_edit_distance function from Aspell.}
  s.test_files = [
    "test/edit_distance_test.rb",
     "test/weights_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

